### ISSUE TITLE
Placement issue of videos.

### ISSUE THREAD

**Issue by calebkrauter** [calebkrauter/susie-creative#7]
Placement issue of videos on[Videos page](file:///D:/Google%20Drive/Projects/GitHub/susie-creative/Videos.html) Videos not fitting length of page on all computers.

**Comment by coltenkrauter** [comment]
Fixed issue, videos will now fill the width of any given viewport symmetrically. @UncleKaleKale may want to investigate how the gap changes when the viewport is resized.
